"""__init__.py module for the Unique Requirement IDs plugin."""

# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

from os.path import join, dirname
from copy import deepcopy
from typing import Any
from aac.execute.plugin_runner import AacCommand
from aac.execute.aac_execution_result import (
    ExecutionResult,
    ExecutionStatus,
    ExecutionMessage,
)
from aac.execute import hookimpl
from aac.context.language_context import LanguageContext
from aac.context.definition import Definition
from aac.in_out.files.aac_file import AaCFile
from aac.execute.plugin_runner import PluginRunner
from aac.context.source_location import SourceLocation


from aac.plugins.unique_requirement_ids.unique_requirement_ids_impl import plugin_name


from aac.plugins.unique_requirement_ids.unique_requirement_ids_impl import (
    requirement_id_is_unique,
)


unique_requirement_ids_aac_file_name = "unique_requirement_ids.aac"


def run_requirement_id_is_unique(context: LanguageContext) -> ExecutionResult:
    """
    Check every requirement to ensure there are no duplication id values defined.

    Args:
        context (LanguageContext): The context in which the constraint is being run.

    Returns:
        The results of the execution of the plugin context constraint.

    """

    return requirement_id_is_unique(context)


@hookimpl
def register_plugin() -> None:
    """
    Registers information about the plugin for use in the CLI.
    """

    active_context = LanguageContext()
    unique_requirement_ids_aac_file = join(
        dirname(__file__), unique_requirement_ids_aac_file_name
    )
    definitions = active_context.parse_and_load(unique_requirement_ids_aac_file)

    unique_requirement_ids_plugin_definition = [
        definition for definition in definitions if definition.name == plugin_name
    ][0]

    plugin_instance = unique_requirement_ids_plugin_definition.instance
    for file_to_load in plugin_instance.definition_sources:
        active_context.parse_and_load(file_to_load)

    plugin_runner = PluginRunner(
        plugin_definition=unique_requirement_ids_plugin_definition
    )

    plugin_runner.add_constraint_callback(
        "Requirement ID is unique", run_requirement_id_is_unique
    )

    active_context.register_plugin_runner(plugin_runner)
