changelog:
  categorgies:
    - title: 'Breaking Changes'
      labels:
        - 'breaking'
        - 'busted'
    - title: 'New Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: 'Bug Fixes'
      labels:
        - 'bug'
        - 'funky'
        - 'Semver-Patch'
    - title: 'Documentation Updates'
      labels:
        - 'documentation'
    - title: 'Other Changes'
      labels:
        - "*"
