tasks:
  - name: Deploy Jekyll Docs
    command: export JEKYLL_ENV=production; cd /workspace/AaC/docs; bundle install && bundle exec jekyll s

  - name: VSCode Extension Environment
    init: |
      cd vscode_extension/
      yarn install
      yarn compile
    command: cd /workspace/AaC/vscode_extension/; yarn watch

  - name: Python Virtual Environment
    init: |
      cd python/
      python3.9 -m venv venv --system-site-packages
      python3.9 -m pip install --upgrade pip
      source venv/bin/activate
      pip install -e .[all]
      aac gen-openapi-spec ../vscode_extension/
      cd ../vscode_extension/
      yarn generate:rest_api
    command: cd /workspace/AaC/python/; source venv/bin/activate # Always launch a console with our virtual env

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python
    - samuelcolvin.jinjahtml
    - vscode.typescript
    - streetsidesoftware.code-spell-checker

image:
  file: .gitpod.Dockerfile
