tasks:
  - name: Deploy Jekyll Docs
    init: |
      cd docs/
      bundle install
      export JEKYLL_ENV=production
    command: cd docs/; bundle exec jekyll s

  - name: VSCode Extension Environment
    init: |
      cd vscode_extension/
      yarn install
      yarn compile
    command: cd vscode_extension/; yarn watch

  - name: Python Virtual Environment
    init: |
      pyenv local install 3.9.0
      pyenv global 3.9.0
      pip install poetry
      cd python/
      poetry install --with development,test
    command: cd python/; poetry shell # Always launch a console with our virtual env

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python
    - samuelcolvin.jinjahtml
    - vscode.typescript
    - streetsidesoftware.code-spell-checker

image:
  file: .gitpod.Dockerfile
