tasks:
  - name: Setup Python Virtual Environment
    init: |
      python3.9 -m venv venv --system-site-packages
      python3.9 -m pip install --upgrade pip
      source venv/bin/activate
      pip install -e .[all]
    command: source venv/bin/activate # Always launch a console with our virtual env

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python
    - samuelcolvin.jinjahtml

image:
  file: .gitpod.Dockerfile
