tasks:
  - name: VSCode Extension Environment
    init: |
      cd vscode_extension/
      npm install
    command: cd vscode_extension/; npm run watch

  - name: Python Virtual Environment
    init: |
      cd python/
      python3.9 -m venv venv --system-site-packages
      python3.9 -m pip install --upgrade pip
      source venv/bin/activate
      pip install -e .[all]
    command: cd python/; source venv/bin/activate # Always launch a console with our virtual env

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python
    - samuelcolvin.jinjahtml
    - vscode.typescript

image:
  file: .gitpod.Dockerfile
