tasks:
  - name: Serve Sphinx Docs
    init: |
      cd /workspace/AaC/docs/
      sleep 120 # Gitpod often takes a long time to install the python environment
      source /workspace/AaC/python/venv/bin/activate
      sphinx-build source gen_docs # Pre-build the docs so that when Gitpod opens the port it's ready to serve
    command: sphinx-autobuild source gen_docs

  - name: VSCode Extension Environment
    init: |
      cd /workspace/AaC/vscode_extension/
      yarn install
      sleep 120 # Gitpod often takes a long time to install the python environment
      source /workspace/AaC/python/venv/bin/activate
      aac gen-openapi-spec
      yarn generate:rest_api
      yarn compile
    command: cd /workspace/AaC/vscode_extension/; yarn watch

  - name: Python Virtual Environment
    init: |
      cd python/
      python3.9 -m venv venv --system-site-packages
      source venv/bin/activate
      pip install -e .[all]
    command: cd /workspace/AaC/python/; source venv/bin/activate # Always launch a console with our virtual env

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python
    - samuelcolvin.jinjahtml
    - vscode.typescript
    - streetsidesoftware.code-spell-checker

image:
  file: .gitpod.Dockerfile
