"""AaC Plugin implementation module for the aac-gen-design-doc plugin."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by the aac gen-plugin, and it won't be overwritten if the file already exists.

plugin_version = "0.0.1"


def gen_design_doc(architecture_files: string[], output_directory: string):
    """
    Generate a System Design Document from Architecture-as-Code models.

    Args:
        architecture_files <string[]>: TODO add a helpful parameter description
        output_directory <string>: TODO add a helpful parameter description
    """

    # TODO add implementation here
    raise NotImplementedError("gen_design_doc is not implemented.")
