"""AaC Plugin implementation module for the aac-spec plugin."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by the aac gen-plugin, and it won't be overwritten if the file already exists.

plugin_version = "0.0.1"


def spec_validate(architecture_file: file, parsed_model: map):
    """
    Validates spec traces within the AaC model.

    Args:
        architecture_file <file>: TODO add a helpful parameter description
        parsed_model <map>: TODO add a helpful parameter description"""

    # TODO add implementation here
    raise NotImplementedError("spec_validate is not implemented.")
