"""__init__.py module for the Required Fields plugin."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

from os.path import join, dirname
from copy import deepcopy
from typing import Any
from aac.execute.plugin_runner import AacCommand
from aac.execute.aac_execution_result import (
    ExecutionResult,
    ExecutionStatus,
    ExecutionMessage,
)
from aac.lang.schema import Schema
from aac.lang.plugininputvalue import PluginInputValue
from aac.execute import hookimpl
from aac.context.language_context import LanguageContext
from aac.context.definition import Definition
from aac.execute.plugin_runner import PluginRunner
from aac.in_out.files.aac_file import AaCFile
from aac.context.source_location import SourceLocation


from aac.plugins.required_fields.required_fields_impl import plugin_name


from aac.plugins.required_fields.required_fields_impl import required_fields_are_present


required_fields_aac_file_name = "required_fields.aac"


def run_required_fields_are_present(
    instance: Any, definition: Definition, defining_schema: Schema, arguments: Any
) -> ExecutionResult:
    """Check every field declared as required is present and populated."""

    return required_fields_are_present(instance, definition, defining_schema)


@hookimpl
def register_plugin() -> None:
    """
    Returns information about the plugin.

    Returns:
        A collection of information about the plugin and what it contributes.
    """

    active_context = LanguageContext()
    required_fields_aac_file = join(dirname(__file__), required_fields_aac_file_name)
    definitions = active_context.parse_and_load(required_fields_aac_file)

    required_fields_plugin_definition = [
        definition for definition in definitions if definition.name == plugin_name
    ][0]

    plugin_instance = required_fields_plugin_definition.instance
    for file_to_load in plugin_instance.definition_sources:
        active_context.parse_and_load(file_to_load)

    plugin_runner = PluginRunner(plugin_definition=required_fields_plugin_definition)

    plugin_runner.add_constraint_callback(
        "Required fields are present", run_required_fields_are_present
    )

    active_context.register_plugin_runner(plugin_runner)
