"""The aac-rest-api plugin module."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by aac gen-plugin, and it won't be overwritten if the file already exists.

from aac.plugins import hookimpl
from aac.cli.aac_command import AacCommand, AacCommandArgument
from aac.package_resources import get_resource_file_contents
from aac.plugins.rest_api.aac_rest_api_impl import rest_api, generate_api


@hookimpl
def get_commands() -> list[AacCommand]:
    """
    Return a list of AacCommands provided by the plugin to register for use.

    This function is automatically generated. Do not edit.

    Returns:
        list of AacCommands
    """
    rest_api_arguments = [
        AacCommandArgument("--host", "Set the hostname of the service. Useful for operating behind proxies."),
        AacCommandArgument("--port", "The port to bing the RESTful service to."),
    ]

    generate_api_arguments = [
        AacCommandArgument("output_directory", "The output directory in which to write the AaC OpenAPI JSON file."),
    ]

    plugin_commands = [
        AacCommand(
            "rest-api",
            "Start a RESTful interface for interacting with and managing AaC.",
            rest_api,
            rest_api_arguments
        ),
        AacCommand(
            "generate-openapi",
            "Write the OpenAPI schema to a JSON file.",
            generate_api,
            generate_api_arguments
        ),
    ]

    return plugin_commands


@hookimpl
def get_plugin_aac_definitions() -> str:
    """
    Return the plugins Aac definitions.

    Returns:
         string representing yaml extensions and definitions defined by the plugin
    """

    return get_resource_file_contents(__package__, "rest_api.yaml")
