# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.contextconstraint import ContextConstraint
from aac.lang.feature import Feature
from feature_test import FeatureTestHelper


class ContextConstraintTestHelper:
    @staticmethod
    def generate_data() -> dict:
        return {
            "name": "test",
            "description": "test",
            "acceptance": [FeatureTestHelper.generate_data()],
        }

    @staticmethod
    def generate_data_required_only() -> dict:
        return {
            "name": "test",
        }


class TestContextConstraint(unittest.TestCase):
    def test_contextconstraint_from_dict_all_fields(self):
        contextconstraint_dict = ContextConstraintTestHelper.generate_data()
        instance = ContextConstraint.from_dict(deepcopy(contextconstraint_dict))
        self.assertEqual(instance.name, contextconstraint_dict["name"])
        self.assertEqual(instance.description, contextconstraint_dict["description"])
        self.assertIsNotNone(instance.acceptance)

        contextconstraint_dict = (
            ContextConstraintTestHelper.generate_data_required_only()
        )
        instance = ContextConstraint.from_dict(deepcopy(contextconstraint_dict))
        self.assertEqual(instance.name, contextconstraint_dict["name"])


if __name__ == "__main__":
    unittest.main()
