# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from aac.lang.generatoroutputtarget import GeneratorOutputTarget


class GeneratorOutputTargetTestHelper:
    @staticmethod
    def generate_data() -> str:
        return "CODE"

    @staticmethod
    def generate_data_required_only() -> str:
        return GeneratorOutputTargetTestHelper.generate_data()


class TestGeneratorOutputTarget(unittest.TestCase):
    def test_generatoroutputtarget_from_dict(self):
        self.assertEqual(
            GeneratorOutputTarget.from_dict("CODE"), GeneratorOutputTarget.CODE
        )
        self.assertEqual(
            GeneratorOutputTarget.from_dict("TEST"), GeneratorOutputTarget.TEST
        )
        self.assertEqual(
            GeneratorOutputTarget.from_dict("DOC"), GeneratorOutputTarget.DOC
        )

        with self.assertRaises(ValueError):
            GeneratorOutputTarget.from_dict("NEVER_GONNA_BE_A_VALID_ENUM_VALUE")


if __name__ == "__main__":
    unittest.main()
