# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.schemaconstraintassignment import SchemaConstraintAssignment
from aac.lang.plugininputvalue import PluginInputValue
from plugininputvalue_test import PluginInputValueTestHelper


class SchemaConstraintAssignmentTestHelper:
    @staticmethod
    def generate_data() -> dict:
        return {
            "name": "test",
            "arguments": [PluginInputValueTestHelper.generate_data()],
        }

    @staticmethod
    def generate_data_required_only() -> dict:
        return {
            "name": "test",
        }


class TestSchemaConstraintAssignment(unittest.TestCase):
    def test_schemaconstraintassignment_from_dict_all_fields(self):
        schemaconstraintassignment_dict = (
            SchemaConstraintAssignmentTestHelper.generate_data()
        )
        instance = SchemaConstraintAssignment.from_dict(
            deepcopy(schemaconstraintassignment_dict)
        )
        self.assertEqual(instance.name, schemaconstraintassignment_dict["name"])
        self.assertIsNotNone(instance.arguments)

        schemaconstraintassignment_dict = (
            SchemaConstraintAssignmentTestHelper.generate_data_required_only()
        )
        instance = SchemaConstraintAssignment.from_dict(
            deepcopy(schemaconstraintassignment_dict)
        )
        self.assertEqual(instance.name, schemaconstraintassignment_dict["name"])


if __name__ == "__main__":
    unittest.main()
