name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
projects: [
  "jondavid-black/AaC Prototype"
]
body:
  - type: checkboxes
    id: pre-requistes
    attributes:
      label: "Pre-requisites"
      description: Please answer the following questions for yourself before submitting an issue.
      options:
      - label: I am running the latest version.
        required: true
      - label: I checked the documentation and found no answer.
        required: true
      - label: I checked to make sure that this issue has not already been filed.
        required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: Please enter a short and explicit description of your incident.
    validations:
      required: true
  - type: input
    id: reproduction-url
    attributes:
      label: "Reproduction URL"
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Reproduction steps"
      value: |
        Please enter an explicit description of your issue
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      value: |
        If applicable, add screenshots to help explain your problem.
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      value: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: textarea
    id: files
    attributes:
      label: "Pertinent Files"
      value: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
