name: " Documentation Request"
description: Create a new ticket for a new feature request
title: "💡 [Documentation] - <title>"
labels: [
  "documentation"
]
projects: [
  "jondavid-black/AaC Prototype"
]
body:
  - type: checkboxes
    id: doc-types
    attributes:
      label: "Documentation Types"
      description: Please select the type(s) of documentation your request relates to.
      options:
        - label: User Documentation
        - label: Developer Documentation
        - label: API Documentation
        - label: New 
        - label: Expansion
        - label: Correction
  - type: textarea
    id: documentation
    attributes:
      label: "Requested Documentation"
      placeholder: Describe in a few lines your documentation request.
    validations:
      required: true
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      placeholder: "Please include any related #<Issues IDs>"
    validations:
      required: false