# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.examplevalue import ExampleValue

TEST_DATA_ALL = {"name": "test", "value": "test"}

TEST_DATA_REQUIRED = {"name": "test", "value": "test"}


class TestExampleValue(unittest.TestCase):
    def test_examplevalue_from_dict_all_fields(self):
        examplevalue_dict = TEST_DATA_ALL
        instance = ExampleValue.from_dict(deepcopy(examplevalue_dict))
        self.assertEqual(instance.name, examplevalue_dict["name"])
        self.assertEqual(instance.value, examplevalue_dict["value"])

        examplevalue_dict = TEST_DATA_REQUIRED
        instance = ExampleValue.from_dict(deepcopy(examplevalue_dict))
        self.assertEqual(instance.name, examplevalue_dict["name"])
        self.assertEqual(instance.value, examplevalue_dict["value"])


if __name__ == "__main__":
    unittest.main()
