# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.requirementparameter import RequirementParameter

TEST_DATA_ALL = {"name": "test", "value": "test"}

TEST_DATA_REQUIRED = {"name": "test", "value": "test"}


class TestRequirementParameter(unittest.TestCase):
    def test_requirementparameter_from_dict_all_fields(self):
        requirementparameter_dict = TEST_DATA_ALL
        instance = RequirementParameter.from_dict(deepcopy(requirementparameter_dict))
        self.assertEqual(instance.name, requirementparameter_dict["name"])
        self.assertEqual(instance.value, requirementparameter_dict["value"])

        requirementparameter_dict = TEST_DATA_REQUIRED
        instance = RequirementParameter.from_dict(deepcopy(requirementparameter_dict))
        self.assertEqual(instance.name, requirementparameter_dict["name"])
        self.assertEqual(instance.value, requirementparameter_dict["value"])


if __name__ == "__main__":
    unittest.main()
