# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.primitiveconstraint import PrimitiveConstraint

TEST_DATA_ALL = {
    "name": "test",
    "description": "test",
    "arguments": [
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
    ],
    "acceptance": [
        {
            "name": "test",
            "background": {"name": "test", "given": ["test", "test"]},
            "scenarios": [
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
            ],
        },
        {
            "name": "test",
            "background": {"name": "test", "given": ["test", "test"]},
            "scenarios": [
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
            ],
        },
    ],
}

TEST_DATA_REQUIRED = {"name": "test"}


class TestPrimitiveConstraint(unittest.TestCase):
    def test_primitiveconstraint_from_dict_all_fields(self):
        primitiveconstraint_dict = TEST_DATA_ALL
        instance = PrimitiveConstraint.from_dict(deepcopy(primitiveconstraint_dict))
        self.assertEqual(instance.name, primitiveconstraint_dict["name"])
        self.assertEqual(instance.description, primitiveconstraint_dict["description"])
        self.assertIsNotNone(instance.arguments)
        self.assertIsNotNone(instance.acceptance)

        primitiveconstraint_dict = TEST_DATA_REQUIRED
        instance = PrimitiveConstraint.from_dict(deepcopy(primitiveconstraint_dict))
        self.assertEqual(instance.name, primitiveconstraint_dict["name"])


if __name__ == "__main__":
    unittest.main()
