# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.primitiveconstraintassignment import PrimitiveConstraintAssignment

TEST_DATA_ALL = {"name": "test", "arguments": "{}"}

TEST_DATA_REQUIRED = {"name": "test"}


class TestPrimitiveConstraintAssignment(unittest.TestCase):
    def test_primitiveconstraintassignment_from_dict_all_fields(self):
        primitiveconstraintassignment_dict = TEST_DATA_ALL
        instance = PrimitiveConstraintAssignment.from_dict(
            deepcopy(primitiveconstraintassignment_dict)
        )
        self.assertEqual(instance.name, primitiveconstraintassignment_dict["name"])
        self.assertEqual(
            instance.arguments, primitiveconstraintassignment_dict["arguments"]
        )

        primitiveconstraintassignment_dict = TEST_DATA_REQUIRED
        instance = PrimitiveConstraintAssignment.from_dict(
            deepcopy(primitiveconstraintassignment_dict)
        )
        self.assertEqual(instance.name, primitiveconstraintassignment_dict["name"])


if __name__ == "__main__":
    unittest.main()
