# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.example import Example
from aac.lang.examplevalue import ExampleValue
from test_aac.lang.test_examplevalue import ExampleValueTestHelper


class ExampleTestHelper:
    @staticmethod
    def generate_data() -> dict:
        return {
            "name": "test",
            "values": [ExampleValueTestHelper.generate_data()],
        }

    @staticmethod
    def generate_data_required_only() -> dict:
        return {
            "name": "test",
            "values": [ExampleValueTestHelper.generate_data_required_only()],
        }


class TestExample(unittest.TestCase):
    def test_example_from_dict_all_fields(self):
        example_dict = ExampleTestHelper.generate_data()
        instance = Example.from_dict(deepcopy(example_dict))
        self.assertEqual(instance.name, example_dict["name"])
        self.assertIsNotNone(instance.values)

        example_dict = ExampleTestHelper.generate_data_required_only()
        instance = Example.from_dict(deepcopy(example_dict))
        self.assertEqual(instance.name, example_dict["name"])
        self.assertIsNotNone(instance.values)


if __name__ == "__main__":
    unittest.main()
