# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.usecasebranch import UsecaseBranch

TEST_DATA_ALL = {"condition": "test", "steps": ["test", "test"]}

TEST_DATA_REQUIRED = {"condition": "test", "steps": ["test", "test"]}


class TestUsecaseBranch(unittest.TestCase):
    def test_usecasebranch_from_dict_all_fields(self):
        usecasebranch_dict = TEST_DATA_ALL
        instance = UsecaseBranch.from_dict(deepcopy(usecasebranch_dict))
        self.assertEqual(instance.condition, usecasebranch_dict["condition"])
        self.assertEqual(instance.steps, usecasebranch_dict["steps"])

        usecasebranch_dict = TEST_DATA_REQUIRED
        instance = UsecaseBranch.from_dict(deepcopy(usecasebranch_dict))
        self.assertEqual(instance.condition, usecasebranch_dict["condition"])
        self.assertEqual(instance.steps, usecasebranch_dict["steps"])


if __name__ == "__main__":
    unittest.main()
