# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from aac.lang.overwriteoption import OverwriteOption


class OverwriteOptionTestHelper:
    @staticmethod
    def generate_data() -> str:
        return "OVERWRITE"

    @staticmethod
    def generate_data_required_only() -> str:
        return OverwriteOptionTestHelper.generate_data()


class TestOverwriteOption(unittest.TestCase):
    def test_overwriteoption_from_dict(self):
        self.assertEqual(
            OverwriteOption.from_dict("OVERWRITE"), OverwriteOption.OVERWRITE
        )
        self.assertEqual(OverwriteOption.from_dict("SKIP"), OverwriteOption.SKIP)

        with self.assertRaises(ValueError):
            OverwriteOption.from_dict("NEVER_GONNA_BE_A_VALID_ENUM_VALUE")


if __name__ == "__main__":
    unittest.main()
