# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.behavior import Behavior

TEST_DATA_ALL = {
    "name": "test",
    "description": "test",
    "tags": ["test", "test"],
    "input": [
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
    ],
    "output": [
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
    ],
    "acceptance": [
        {
            "name": "test",
            "background": {"name": "test", "given": ["test", "test"]},
            "scenarios": [
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
            ],
        },
        {
            "name": "test",
            "background": {"name": "test", "given": ["test", "test"]},
            "scenarios": [
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
            ],
        },
    ],
    "requirements": ["test", "test"],
}

TEST_DATA_REQUIRED = {"name": "test"}


class TestBehavior(unittest.TestCase):
    def test_behavior_from_dict_all_fields(self):
        behavior_dict = TEST_DATA_ALL
        instance = Behavior.from_dict(deepcopy(behavior_dict))
        self.assertEqual(instance.name, behavior_dict["name"])
        self.assertEqual(instance.description, behavior_dict["description"])
        self.assertEqual(instance.tags, behavior_dict["tags"])
        self.assertIsNotNone(instance.input)
        self.assertIsNotNone(instance.output)
        self.assertIsNotNone(instance.acceptance)
        self.assertEqual(instance.requirements, behavior_dict["requirements"])

        behavior_dict = TEST_DATA_REQUIRED
        instance = Behavior.from_dict(deepcopy(behavior_dict))
        self.assertEqual(instance.name, behavior_dict["name"])


if __name__ == "__main__":
    unittest.main()
