# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.example import Example

TEST_DATA_ALL = {
    "name": "test",
    "values": [{"name": "test", "value": "test"}, {"name": "test", "value": "test"}],
}

TEST_DATA_REQUIRED = {
    "name": "test",
    "values": [{"name": "test", "value": "test"}, {"name": "test", "value": "test"}],
}


class TestExample(unittest.TestCase):
    def test_example_from_dict_all_fields(self):
        example_dict = TEST_DATA_ALL
        instance = Example.from_dict(deepcopy(example_dict))
        self.assertEqual(instance.name, example_dict["name"])
        self.assertIsNotNone(instance.values)

        example_dict = TEST_DATA_REQUIRED
        instance = Example.from_dict(deepcopy(example_dict))
        self.assertEqual(instance.name, example_dict["name"])
        self.assertIsNotNone(instance.values)


if __name__ == "__main__":
    unittest.main()
