# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.generator import Generator

TEST_DATA_ALL = {
    "name": "test",
    "description": "test",
    "sources": [
        {
            "name": "test",
            "data_source": "test",
            "data_content": "test",
            "templates": [
                {
                    "name": "test",
                    "description": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "helper_functions": [
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                    ],
                    "output_target": "CODE",
                    "output_path_uses_data_source_package": True,
                    "output_file_prefix": "test",
                    "output_file_name": "test",
                    "output_file_suffix": "test",
                    "output_file_extension": "test",
                },
                {
                    "name": "test",
                    "description": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "helper_functions": [
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                    ],
                    "output_target": "CODE",
                    "output_path_uses_data_source_package": True,
                    "output_file_prefix": "test",
                    "output_file_name": "test",
                    "output_file_suffix": "test",
                    "output_file_extension": "test",
                },
            ],
        },
        {
            "name": "test",
            "data_source": "test",
            "data_content": "test",
            "templates": [
                {
                    "name": "test",
                    "description": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "helper_functions": [
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                    ],
                    "output_target": "CODE",
                    "output_path_uses_data_source_package": True,
                    "output_file_prefix": "test",
                    "output_file_name": "test",
                    "output_file_suffix": "test",
                    "output_file_extension": "test",
                },
                {
                    "name": "test",
                    "description": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "helper_functions": [
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                        {
                            "name": "test",
                            "description": "test",
                            "package": "test",
                            "module": "test",
                            "function": "test",
                        },
                    ],
                    "output_target": "CODE",
                    "output_path_uses_data_source_package": True,
                    "output_file_prefix": "test",
                    "output_file_name": "test",
                    "output_file_suffix": "test",
                    "output_file_extension": "test",
                },
            ],
        },
    ],
}

TEST_DATA_REQUIRED = {
    "name": "test",
    "sources": [
        {
            "name": "test",
            "data_source": "test",
            "templates": [
                {
                    "name": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "output_target": "CODE",
                    "output_file_extension": "test",
                },
                {
                    "name": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "output_target": "CODE",
                    "output_file_extension": "test",
                },
            ],
        },
        {
            "name": "test",
            "data_source": "test",
            "templates": [
                {
                    "name": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "output_target": "CODE",
                    "output_file_extension": "test",
                },
                {
                    "name": "test",
                    "template_file": "test",
                    "overwrite": "OVERWRITE",
                    "output_target": "CODE",
                    "output_file_extension": "test",
                },
            ],
        },
    ],
}


class TestGenerator(unittest.TestCase):
    def test_generator_from_dict_all_fields(self):
        generator_dict = TEST_DATA_ALL
        instance = Generator.from_dict(deepcopy(generator_dict))
        self.assertEqual(instance.name, generator_dict["name"])
        self.assertEqual(instance.description, generator_dict["description"])
        self.assertIsNotNone(instance.sources)

        generator_dict = TEST_DATA_REQUIRED
        instance = Generator.from_dict(deepcopy(generator_dict))
        self.assertEqual(instance.name, generator_dict["name"])
        self.assertIsNotNone(instance.sources)


if __name__ == "__main__":
    unittest.main()
