# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.projectdependency import ProjectDependency

TEST_DATA_ALL = {"name": "test", "version": "test"}

TEST_DATA_REQUIRED = {"name": "test", "version": "test"}


class TestProjectDependency(unittest.TestCase):
    def test_projectdependency_from_dict_all_fields(self):
        projectdependency_dict = TEST_DATA_ALL
        instance = ProjectDependency.from_dict(deepcopy(projectdependency_dict))
        self.assertEqual(instance.name, projectdependency_dict["name"])
        self.assertEqual(instance.version, projectdependency_dict["version"])

        projectdependency_dict = TEST_DATA_REQUIRED
        instance = ProjectDependency.from_dict(deepcopy(projectdependency_dict))
        self.assertEqual(instance.name, projectdependency_dict["name"])
        self.assertEqual(instance.version, projectdependency_dict["version"])


if __name__ == "__main__":
    unittest.main()
