# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.aacimport import AacImport


class AacImportTestHelper:
    @staticmethod
    def generate_data() -> dict:
        return {
            "files": ["test"],
        }

    @staticmethod
    def generate_data_required_only() -> dict:
        return {
            "files": ["test"],
        }


class TestAacImport(unittest.TestCase):
    def test_aacimport_from_dict_all_fields(self):
        aacimport_dict = AacImportTestHelper.generate_data()
        instance = AacImport.from_dict(deepcopy(aacimport_dict))
        self.assertEqual(instance.files, aacimport_dict["files"])

        aacimport_dict = AacImportTestHelper.generate_data_required_only()
        instance = AacImport.from_dict(deepcopy(aacimport_dict))
        self.assertEqual(instance.files, aacimport_dict["files"])


if __name__ == "__main__":
    unittest.main()
