# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.scenario import Scenario
from aac.lang.example import Example
from .test_example import ExampleTestHelper


class ScenarioTestHelper:
    @staticmethod
    def generate_data() -> dict:
        return {
            "name": "test",
            "tags": ["test"],
            "given": ["test"],
            "when": ["test"],
            "then": ["test"],
            "examples": ExampleTestHelper.generate_data(),
        }

    @staticmethod
    def generate_data_required_only() -> dict:
        return {
            "name": "test",
            "when": ["test"],
            "then": ["test"],
        }


class TestScenario(unittest.TestCase):
    def test_scenario_from_dict_all_fields(self):
        scenario_dict = ScenarioTestHelper.generate_data()
        instance = Scenario.from_dict(deepcopy(scenario_dict))
        self.assertEqual(instance.name, scenario_dict["name"])
        self.assertEqual(instance.tags, scenario_dict["tags"])
        self.assertEqual(instance.given, scenario_dict["given"])
        self.assertEqual(instance.when, scenario_dict["when"])
        self.assertEqual(instance.then, scenario_dict["then"])
        self.assertIsNotNone(instance.examples)

        scenario_dict = ScenarioTestHelper.generate_data_required_only()
        instance = Scenario.from_dict(deepcopy(scenario_dict))
        self.assertEqual(instance.name, scenario_dict["name"])
        self.assertEqual(instance.when, scenario_dict["when"])
        self.assertEqual(instance.then, scenario_dict["then"])


if __name__ == "__main__":
    unittest.main()
