# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.schemaconstraint import SchemaConstraint

TEST_DATA_ALL = {
    "name": "test",
    "description": "test",
    "universal": True,
    "arguments": [
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
        {
            "name": "test",
            "type": "test",
            "description": "test",
            "is_required": True,
            "default": "test",
        },
    ],
    "acceptance": [
        {
            "name": "test",
            "background": {"name": "test", "given": ["test", "test"]},
            "scenarios": [
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
            ],
        },
        {
            "name": "test",
            "background": {"name": "test", "given": ["test", "test"]},
            "scenarios": [
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
                {
                    "name": "test",
                    "tags": ["test", "test"],
                    "given": ["test", "test"],
                    "when": ["test", "test"],
                    "then": ["test", "test"],
                    "examples": {
                        "name": "test",
                        "values": [
                            {"name": "test", "value": "test"},
                            {"name": "test", "value": "test"},
                        ],
                    },
                },
            ],
        },
    ],
}

TEST_DATA_REQUIRED = {"name": "test"}


class TestSchemaConstraint(unittest.TestCase):
    def test_schemaconstraint_from_dict_all_fields(self):
        schemaconstraint_dict = TEST_DATA_ALL
        instance = SchemaConstraint.from_dict(deepcopy(schemaconstraint_dict))
        self.assertEqual(instance.name, schemaconstraint_dict["name"])
        self.assertEqual(instance.description, schemaconstraint_dict["description"])
        self.assertEqual(instance.universal, schemaconstraint_dict["universal"])
        self.assertIsNotNone(instance.arguments)
        self.assertIsNotNone(instance.acceptance)

        schemaconstraint_dict = TEST_DATA_REQUIRED
        instance = SchemaConstraint.from_dict(deepcopy(schemaconstraint_dict))
        self.assertEqual(instance.name, schemaconstraint_dict["name"])


if __name__ == "__main__":
    unittest.main()
