# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.requirementparameter import RequirementParameter


class RequirementParameterTestHelper:
    @staticmethod
    def generate_data() -> dict:
        return {
            "name": "test",
            "value": "test",
        }

    @staticmethod
    def generate_data_required_only() -> dict:
        return {
            "name": "test",
            "value": "test",
        }


class TestRequirementParameter(unittest.TestCase):
    def test_requirementparameter_from_dict_all_fields(self):
        requirementparameter_dict = RequirementParameterTestHelper.generate_data()
        instance = RequirementParameter.from_dict(deepcopy(requirementparameter_dict))
        self.assertEqual(instance.name, requirementparameter_dict["name"])
        self.assertEqual(instance.value, requirementparameter_dict["value"])

        requirementparameter_dict = (
            RequirementParameterTestHelper.generate_data_required_only()
        )
        instance = RequirementParameter.from_dict(deepcopy(requirementparameter_dict))
        self.assertEqual(instance.name, requirementparameter_dict["name"])
        self.assertEqual(instance.value, requirementparameter_dict["value"])


if __name__ == "__main__":
    unittest.main()
