# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.aacimport import AacImport

TEST_DATA_ALL = {"files": ["test", "test"]}

TEST_DATA_REQUIRED = {"files": ["test", "test"]}


class TestAacImport(unittest.TestCase):
    def test_aacimport_from_dict_all_fields(self):
        aacimport_dict = TEST_DATA_ALL
        instance = AacImport.from_dict(deepcopy(aacimport_dict))
        self.assertEqual(instance.files, aacimport_dict["files"])

        aacimport_dict = TEST_DATA_REQUIRED
        instance = AacImport.from_dict(deepcopy(aacimport_dict))
        self.assertEqual(instance.files, aacimport_dict["files"])


if __name__ == "__main__":
    unittest.main()
