# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.schemaconstraintassignment import SchemaConstraintAssignment

TEST_DATA_ALL = {"name": "test", "arguments": "{}"}

TEST_DATA_REQUIRED = {"name": "test"}


class TestSchemaConstraintAssignment(unittest.TestCase):
    def test_schemaconstraintassignment_from_dict_all_fields(self):
        schemaconstraintassignment_dict = TEST_DATA_ALL
        instance = SchemaConstraintAssignment.from_dict(
            deepcopy(schemaconstraintassignment_dict)
        )
        self.assertEqual(instance.name, schemaconstraintassignment_dict["name"])
        self.assertEqual(
            instance.arguments, schemaconstraintassignment_dict["arguments"]
        )

        schemaconstraintassignment_dict = TEST_DATA_REQUIRED
        instance = SchemaConstraintAssignment.from_dict(
            deepcopy(schemaconstraintassignment_dict)
        )
        self.assertEqual(instance.name, schemaconstraintassignment_dict["name"])


if __name__ == "__main__":
    unittest.main()
