# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.schemaextension import SchemaExtension


class SchemaExtensionTestHelper:
    @staticmethod
    def generate_data() -> dict:
        return {
            "package": "test",
            "name": "test",
        }

    @staticmethod
    def generate_data_required_only() -> dict:
        return {
            "package": "test",
            "name": "test",
        }


class TestSchemaExtension(unittest.TestCase):
    def test_schemaextension_from_dict_all_fields(self):
        schemaextension_dict = SchemaExtensionTestHelper.generate_data()
        instance = SchemaExtension.from_dict(deepcopy(schemaextension_dict))
        self.assertEqual(instance.package, schemaextension_dict["package"])
        self.assertEqual(instance.name, schemaextension_dict["name"])

        schemaextension_dict = SchemaExtensionTestHelper.generate_data_required_only()
        instance = SchemaExtension.from_dict(deepcopy(schemaextension_dict))
        self.assertEqual(instance.package, schemaextension_dict["package"])
        self.assertEqual(instance.name, schemaextension_dict["name"])


if __name__ == "__main__":
    unittest.main()
