# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import unittest
from copy import deepcopy
from aac.lang.aactype import AacType

TEST_DATA_ALL = {"name": "test", "package": "test", "description": "test"}

TEST_DATA_REQUIRED = {"name": "test", "package": "test"}


class TestAacType(unittest.TestCase):
    def test_aactype_from_dict_all_fields(self):
        aactype_dict = TEST_DATA_ALL
        instance = AacType.from_dict(deepcopy(aactype_dict))
        self.assertEqual(instance.name, aactype_dict["name"])
        self.assertEqual(instance.package, aactype_dict["package"])
        self.assertEqual(instance.description, aactype_dict["description"])

        aactype_dict = TEST_DATA_REQUIRED
        instance = AacType.from_dict(deepcopy(aactype_dict))
        self.assertEqual(instance.name, aactype_dict["name"])
        self.assertEqual(instance.package, aactype_dict["package"])


if __name__ == "__main__":
    unittest.main()
