# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.


Feature: Success path testing

  Scenario: Simple Happy Test
  
      Given An AaC file containing schemas with no extra fields.
      When The AaC check command is run on the schema.
      Then The AaC check command is run on the schema.
      
    
  
  