"""Setup.py module for the aac-gen-protobuf plugin."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.
from aac_gen_protobuf.aac_gen_protobuf_impl import plugin_version
from setuptools import setup

setup(
    version=plugin_version,
    name="aac-gen-protobuf",
    install_requires=["aac"],
    entry_points={
        "aac": ["aac_gen_protobuf=aac_gen_protobuf.aac_gen_protobuf"],
    }
)
