name: Deploy Python Artifacts

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./python

jobs:
  Build_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@1e3f89c23eb6583116848d81ccd5ad952f9a62b6

  Deploy-Artifacts:
    runs-on: ubuntu-latest
    needs: Build_Artifacts
    steps:
      - name: Download API Documentation
        uses: actions/download-artifact@v2
        with:
          name: api-documentation
          path: docs/build/html/

      - name: Github Pages and Sphinx Deployment
        run: echo "This is where I'd deploy if I were setup"

      - name: Download Python Wheel
        uses: actions/download-artifact@v2
        with:
          name: aac_wheel
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}


