"""Python module for the GeneratorOutputTarget enumeration."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

from enum import Enum, auto


class GeneratorOutputTarget(Enum):
    CODE = auto()
    TEST = auto()
    DOC = auto()

    @classmethod
    def from_dict(cls, d: str):
        if "CODE" == d:
            return cls.CODE
        if "TEST" == d:
            return cls.TEST
        if "DOC" == d:
            return cls.DOC

        raise ValueError(f"Invalid value {d} for GeneratorOutputTarget")
