"""Python module for the OverwriteOption enumeration."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

from enum import Enum, auto


class OverwriteOption(Enum):
    OVERWRITE = auto()
    SKIP = auto()

    @classmethod
    def from_dict(cls, d: str):
        if "OVERWRITE" == d:
            return cls.OVERWRITE
        if "SKIP" == d:
            return cls.SKIP

        raise ValueError(f"Invalid value {d} for OverwriteOption")
