"""Python module for the PluginCommandReference class."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

from dataclasses import dataclass
import attr
from typing import Optional
from attr import attrib, validators


@dataclass(frozen=True)
class PluginCommandReference:
    """
    A plugin command reference that can be used to establish cross-plugin behaviors.

    plugin: str - The name of the plugin to reference.
    command: str - The name of the command to reference.
    """

    plugin: str = attrib(init=attr.ib(), validator=validators.instance_of(str))
    command: str = attrib(init=attr.ib(), validator=validators.instance_of(str))

    @classmethod
    def from_dict(cls, data):
        return cls(**data)
