"""Python module for the SchemaExtension class."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

from dataclasses import dataclass
import attr
from typing import Optional
from attr import attrib, validators


@dataclass(frozen=True)
class SchemaExtension:
    """
    References the inheritance parent schema.

    package: str - The package name of the inheritance parent schema.
    name: str - The name of the inheritance parent schema.
    """

    package: str = attrib(init=attr.ib(), validator=validators.instance_of(str))
    name: str = attrib(init=attr.ib(), validator=validators.instance_of(str))

    @classmethod
    def from_dict(cls, data):
        args = {}

        return cls(**args, **data)
