"""AaC Plugin implementation module for the aac-gen-protobuf plugin."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by the aac gen-plugin, and it won't be overwritten if the file already exists.

plugin_version = "0.0.1"


def gen_protobuf(architecture_file: str, output_directory: str):
    """
    Generate protobuf messages from Arch-as-Code models.

    Args:
        architecture_file <str>: TODO add a helpful parameter description
        output_directory <str>: TODO add a helpful parameter description
    """

    # TODO add implementation here
    raise NotImplementedError("gen_protobuf is not implemented.")
