"""AaC Plugin implementation module for the material_model plugin."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by the aac gen-plugin, and it won't be overwritten if the file already exists.

from aac.plugins.plugin_execution import PluginExecutionResult, plugin_result

plugin_name = "material_model"


def gen_bom(architecture_file: str, output_directory: str) -> PluginExecutionResult:
    """
    Generate a Bill of Material from Arch-as-Code material models.

    Args:
        architecture_file (str): The yaml file containing the material models to generate the BOM.
        output_directory (str): The directory to write the generated BOM to.
    """
    # TODO add implementation here
    def _implement_and_rename_me():
        raise NotImplementedError("gen_bom is not implemented.")

    with plugin_result(plugin_name, _implement_and_rename_me) as result:
        return result
