"""Generated AaC Plugin hookimpls module for the aac-plantuml plugin."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import aac
from aac.AacCommand import AacCommand
from aac_plantuml_impl import puml_component, puml_sequence, puml_object


@aac.hookimpl
def get_commands() -> list[AacCommand]:
    """
    Return a list of AacCommands provided by the plugin to register for use.

    This function is automatically generated. Do not edit.

    :returns: list of AacCommands
    """
    plugin_commands = [
        AacCommand("puml-component", "Converts an AaC model to Plant ULM component diagram.", puml_component),
        AacCommand("puml-sequence", "Converts an AaC usecase to Plant ULM sequence diagram.", puml_sequence),
        AacCommand("puml-object", "Converts an AaC model to Plant ULM object diagram.", puml_object),
    ]

    return plugin_commands

