"""The start-lsp plugin module."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by aac gen-plugin, and it won't be overwritten if the file already exists.

from aac.cli.aac_command import AacCommand, AacCommandArgument
from aac.plugins import hookimpl
from aac.plugins.start_lsp.start_lsp_impl import start_lsp


@hookimpl
def get_commands() -> list[AacCommand]:
    """
    Return a list of AacCommands provided by the plugin to register for use.

    This function is automatically generated. Do not edit.

    Returns:
        list of AacCommands
    """
    plugin_commands = [
        AacCommand(
            "start-lsp",
            "Start the AaC Language Server Protocol (LSP) server",
            start_lsp,
            [
                AacCommandArgument("--host", "The host to use for connections"),
                AacCommandArgument("--port", "The port to use for connections"),
            ]
        ),
    ]

    return plugin_commands
