"""Generated AaC Plugin hookimpls module for the aac-spec plugin."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED
# This file is auto-generated by the aac gen-plugin and may be overwritten.

import aac
from aac.AacCommand import AacCommand
from aac_spec_impl import spec_validate


@aac.hookimpl
def get_commands() -> list[AacCommand]:
    """
    Return a list of AacCommands provided by the plugin to register for use.

    This function is automatically generated. Do not edit.

    Returns:
        list of AacCommands
    """
    plugin_commands = [
        AacCommand("spec-validate", "Validates spec traces within the AaC model.", spec_validate),
    ]

    return plugin_commands


@aac.hookimpl
def get_base_model_extensions() -> str:
    """
    Return data and ext definitions to apply to the AaC base.

    Returns:
        string representing yaml extensions and data definitions employed by the plugin
    """
    return PLUGIN_EXTENSION_YAML


PLUGIN_EXTENSION_YAML = """
data:
  name: Specification
  fields:
    - name: title
      type: string
    - name: abbrv
      type: string
    - name: description
      type: string
    - name: subspecs
      type: string[]
    - name: sections
      type: SpecSection[]
    - name: requirements
      type: Requirement[]
  required:
    - title
    - abbrv
---
data:
  name: SpecSection
  fields:
    - name: name
      type: string
    - name: description
      type: string
    - name: requirements
      type: Requirement[]
  required:
    - name
---
data:
  name: Requirement
  fields:
    - name: id
      type: string
    - name: shall
      type: string
    - name: parent
      type: RequirementReference[]
    - name: attributes
      type: RequirementAttribute[]
  required:
    - id
    - shall
---
data:
  name: RequirementAttribute
  fields:
    - name: name
      type: string
    - name: value
      type: string
  required:
    - name
    - value
---
data:
  name: RequirementReference
  fields:
    - name: abbrv
      type: string
    - name: ids
      type: string[]
  required:
    - spec
    - ids
---
ext:
  name: addSpecificationToRoot
  type: root
  dataExt:
    add:
      - name: spec
        type: Specification
---
ext:
  name: addSpecTraceToBehavior
  type: Behavior
  dataExt:
    add:
      - name: requirements
        type: RequirementReference[]
---
ext:
  name: addSpecTraceToData
  type: data
  dataExt:
    add:
      - name: requirements
        type: RequirementReference[]
"""
