"""AaC Plugin implementation module for the aac-spec plugin."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by the aac gen-plugin, and it won't be overwritten if the file already exists.
from aac import util, parser

plugin_version = "0.0.1"


def spec_validate(architecture_file: str):
    """
    Validates spec traces within the AaC model.

    Args:
        architecture_file (file): The file to validate for spec cross-references.
    """

    parsed_model = parser.parse_file(architecture_file)

    # go through the parsed model to find requirement references
    req_refs = []
    req_refs.extend(util.search(parsed_model, ["spec", "requirements", "parent"]))
    req_refs.extend(util.search(parsed_model, ["model", "behavior", "requirements"]))
    req_refs.extend(util.search(parsed_model, ["data", "requirements"]))

    print("Found the following requirement references:")
    print(req_refs)

    raise NotImplementedError("spec_validate is not implemented.")
