"""AaC Plugin implementation module for the aac-spec plugin."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by the aac gen-plugin, and it won't be overwritten if the file already exists.

plugin_version = "0.0.1"


def spec_validate(architecture_file: str, parsed_model: dict):
    """
    Validates spec traces within the AaC model.

    :param architecture_file: Path to the architecture_file
    :type  architecture_file: str
    :param parsed_model: Dict obj representing a yaml plugin model
    :type  parsed_model: map
    """

    # TODO add implementation here
    raise NotImplementedError("spec_validate is not implemented.")
