# WARNIG - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED
# This file is auto-generated by aac gen-plugin and may be overwritten.

import aac
from aac.AacCommand import AacCommand
from aac_spec_impl import spec_validate


@aac.hookimpl
def get_commands():
    ret_val = []
    ret_val.append(AacCommand(
        "spec-validate",
        '''
        Validates spec traces within the AaC model
        ''', spec_validate)
    )
    return ret_val


@aac.hookimpl
def get_base_model_extensions() -> str:
    return '''
data:
  fields:
  - name: name
    type: string
  - name: description
    type: string
  - name: subspecs
    type: string[]
  - name: sections
    type: SpecSection[]
  - name: requirements
    type: Requirement[]
  name: Specification
  required:
  - name

---
data:
  fields:
  - name: name
    type: string
  - name: description
    type: string
  - name: requirements
    type: Requirement[]
  name: SpecSection
  required:
  - name

---
data:
  fields:
  - name: id
    type: string
  - name: shall
    type: string
  - name: parent
    type: string
  - name: attributes
    type: RequirementAttribute[]
  name: Requirement
  required:
  - id
  - shall

---
data:
  fields:
  - name: name
    type: string
  - name: value
    type: string
  name: RequirementAttribute
  required:
  - name
  - value

---
ext:
  dataExt:
    add:
    - name: spec
      type: Specification
  name: addSpecificationToRoot
  type: root

'''
