"""AaC Plugin implementation module for the aac-gen-gherkin-behaviors plugin."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by the aac gen-plugin, and it won't be overwritten if the file already exists.

from aac import parser, util
from aac.template_engine import (
    TemplateOutputFile,
    generate_template,
    load_templates,
    write_generated_templates_to_file,
)


plugin_version = "0.0.1"


def gen_gherkin_behaviors(architecture_file: str, output_directory: str):
    """
    Generate Gherkin feature files from Arch-as-Code model behavior scenarios.

    Args:
        architecture_file (str): The yaml file containing the data models to generate as Gherkin feature files.
        output_directory (str): The directory to write the generated Gherkin feature files to.
    """

    parsed_models = parser.parse_file(architecture_file)

    loaded_templates = load_templates(__package__)

    message_template_properties = _get_template_properties(parsed_models)
    generated_template_messages = _generate_gherkin_feature_files(loaded_templates, message_template_properties)

    write_generated_templates_to_file(generated_template_messages, output_directory)
    print(f"Successfully generated templates to directory: {output_directory}")


def _get_template_properties(parsed_models: dict) -> dict[str, dict]:
    """
    Generates a list of template properties dictionaries for each gherkin feature file to generate.

    Args:
        parsed_models: a dict of models where the key is the model name and the value is the model dict

    Returns:
        a list of template property dicts
    """
    return


def _generate_gherkin_feature_files(gherkin_templates: list, properties: list[dict]) -> list[TemplateOutputFile]:
    """
    Compiles templates with variable properties information.

    Args:
        gherkin_templates: templates to generate against. (Should only be one template)
        properties: a list of dicts of properties

    Returns:
        list of template information dictionaries.
    """
    return
