"""The start-lsp plugin module."""
# NOTE: It is safe to edit this file.
# This file is only initially generated by aac gen-plugin, and it won't be overwritten if the file already exists.

from aac.plugins import hookimpl
from aac.cli.aac_command import AacCommand, AacCommandArgument
from aac.cli.builtin_commands.start_lsp.start_lsp_impl import start_lsp


@hookimpl
def get_commands() -> list[AacCommand]:
    """
    Return a list of AacCommands provided by the plugin to register for use.

    This function is automatically generated. Do not edit.

    Returns:
        list of AacCommands
    """
    start_lsp_arguments = [
        AacCommandArgument("--dev", "Start the server in development mode.", data_type="bool", action="store_true"),
    ]

    plugin_commands = [
        AacCommand(
            "start-lsp",
            "Start the AaC Language Server Protocol (LSP) server",
            start_lsp,
            start_lsp_arguments
        ),
    ]

    return plugin_commands
