# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch AaC Workflow

on:
  push:
    branches: [main]

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-job.yml@70937f95f9312e5a1e3f622249dcc6f3315987bd

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@70937f95f9312e5a1e3f622249dcc6f3315987bd

  Deploy_Artifacts:
    needs: Run_Functional_Tests
    uses: jondavid-black/AaC/.github/workflows/deploy-artifacts.yml@70937f95f9312e5a1e3f622249dcc6f3315987bd
