name: Deploy VSCode Artifacts

on:
  pull_request:

jobs:
  build_python_artifacts:
    name: Build Python Artifacts
    uses: jondavid-black/AaC/.github/workflows/python-build-artifacts.yml@d96207706dddd99eb7778982ccbb0c572bb5f8a1

  build_deployment_artifacts:
    name: Build VSCode Artifacts
    uses: jondavid-black/AaC/.github/workflows/vscode-build-artifacts.yml@d96207706dddd99eb7778982ccbb0c572bb5f8a1
    needs: build_python_artifacts

  deploy_artifacts:
    name: Deploy Artifacts
    runs-on: ubuntu-latest
    needs: build_deployment_artifacts
    steps:
      - name: Get Extension Artifact
        uses: actions/download-artifact@v2
        with:
          name: aac.vsix
          path: vscode_extension/aac.vsix

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToMsMarket
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: vscode_extension/aac.vsix
          yarn: true

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: vscode_extension/aac.vsix
          yarn: true
